### ISSUE TITLE
Re-release 0.18.0

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto-client#124]
금일 0.18.0으로 릴리즈 되었으나, 필요한 부분이 누락 되어 있는 것이 뒤늦게 발견(https://github.com/aicers/giganto-client/issues/123) 되어서, 기존의 tag를 취소하고 다시 tagging 합니다.

**Comment by msk** [comment]
Thank you for the update and for your continuous efforts on the giganto-client project. However, I would like to express a concern regarding the modification of a public tag. As a public project, it is generally considered best practice to avoid modifying or deleting tags after they have been released. This can create confusion and potential issues for users who have already pulled the original version.

Instead of modifying the existing tag, it might be more appropriate to release a new version with the required fixes. This approach maintains a clear and consistent release history and ensures that anyone relying on the 0.18.0 version is not disrupted.

**Comment by kimhanbeom** [comment]
Thank you for your kind explanation. I will close this issue and open a new release issue.
